Merge upstream release 0.27

diff --git a/check/check-missing b/check/check-missing
--- a/check/check-missing
+++ b/check/check-missing
@@ -1,23 +1,26 @@
 #! /bin/sh
 
-# Make sure we're POSIX
-if [ "$PKG_CONFIG_SHELL_IS_POSIX" != "1" ]; then
-    PKG_CONFIG_SHELL_IS_POSIX=1 PATH=`getconf PATH` exec sh $0 "$@"
-fi
+set -e
 
 . ${srcdir}/common
 
 # non-existent package; call should fail and cause no output
 EXPECT_RETURN=1
 RESULT=""
-ARGS="pkg-non-existent"
+ARGS="--exists pkg-non-existent"
+run_test
+
+# existing package, but with missing Requires
+EXPECT_RETURN=1
+RESULT=""
+ARGS="--exists missing-requires"
 run_test
 
 # tests below are on an existing package, but with missing Requires.private;
 # when pkg-config outputs error, the actual error text isn't checked
-# package exists
-ARGS="missing-requires-private"
-EXPECT_RETURN=0
+# package exists, but should fail since deps can't be resolved
+ARGS="--exists missing-requires-private"
+EXPECT_RETURN=1
 RESULT=""
 run_test
 
